'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OnVac_Orari
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''OnitLayout31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitLayout31 As Global.Onit.Controls.PagesLayout.OnitLayout3
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LayoutTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutTitolo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ToolBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBar As Global.Infragistics.WebUI.UltraWebToolbar.UltraWebToolbar
    
    '''<summary>
    '''Div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LayoutTitolo_sezioneCnv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutTitolo_sezioneCnv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pan_orari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_orari As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TABLE1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TABLE1 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''or1_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or1_0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or1_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or1_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or1_3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or2_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or2_0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or2_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or2_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or2_3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or3_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or3_0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or3_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or3_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or3_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or3_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or3_3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or4_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or4_0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or4_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or4_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or4_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or4_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or4_3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or5_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or5_0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or5_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or5_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or5_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or5_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or5_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or5_3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or6_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or6_0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or6_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or6_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or6_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or6_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or6_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or6_3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or0_0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or0_0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or0_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or0_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or0_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or0_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or0_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or0_3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LayoutTitolo_sezioneCnvApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutTitolo_sezioneCnvApp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pan_orari_app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_orari_app As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''or1_0app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or1_0app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or1_1app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or1_1app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or1_2app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or1_2app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or1_3app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or1_3app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or2_0app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or2_0app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or2_1app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or2_1app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or2_2app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or2_2app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or2_3app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or2_3app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or3_0app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or3_0app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or3_1app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or3_1app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or3_2app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or3_2app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or3_3app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or3_3app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or4_0app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or4_0app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or4_1app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or4_1app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or4_2app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or4_2app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or4_3app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or4_3app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or5_0app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or5_0app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or5_1app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or5_1app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or5_2app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or5_2app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or5_3app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or5_3app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or6_0app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or6_0app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or6_1app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or6_1app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or6_2app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or6_2app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or6_3app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or6_3app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or0_0app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or0_0app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or0_1app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or0_1app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or0_2app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or0_2app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''or0_3app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents or0_3app As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lb_warning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_warning As Global.System.Web.UI.WebControls.Label
End Class
