'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
'
Namespace wsBatch
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsBatchSoap", [Namespace]:="http://tempuri.org/wsBatch/wsBatch"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BasePort)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(PortParameter()))>  _
    Partial Public Class wsBatch
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreateJobOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ResumeJobOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ResumeJobUpdateTotalItemsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetJobInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetJobsIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Onit.OnAssistnet.OnVac.My.MySettings.Default.Onit_OnAssistnet_OnVac_Web_wsBatch_wsBatch
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreateJobCompleted As CreateJobCompletedEventHandler
        
        '''<remarks/>
        Public Event ResumeJobCompleted As ResumeJobCompletedEventHandler
        
        '''<remarks/>
        Public Event ResumeJobUpdateTotalItemsCompleted As ResumeJobUpdateTotalItemsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetJobInfoCompleted As GetJobInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetJobsIdCompleted As GetJobsIdCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsBatch/wsBatch/CreateJob", RequestNamespace:="http://tempuri.org/wsBatch/wsBatch", ResponseNamespace:="http://tempuri.org/wsBatch/wsBatch", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateJob(ByVal jobInputData As JobInputData) As Long
            Dim results() As Object = Me.Invoke("CreateJob", New Object() {jobInputData})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Function BeginCreateJob(ByVal jobInputData As JobInputData, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateJob", New Object() {jobInputData}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreateJob(ByVal asyncResult As System.IAsyncResult) As Long
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateJobAsync(ByVal jobInputData As JobInputData)
            Me.CreateJobAsync(jobInputData, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateJobAsync(ByVal jobInputData As JobInputData, ByVal userState As Object)
            If (Me.CreateJobOperationCompleted Is Nothing) Then
                Me.CreateJobOperationCompleted = AddressOf Me.OnCreateJobOperationCompleted
            End If
            Me.InvokeAsync("CreateJob", New Object() {jobInputData}, Me.CreateJobOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateJobOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateJobCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateJobCompleted(Me, New CreateJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsBatch/wsBatch/ResumeJob", RequestNamespace:="http://tempuri.org/wsBatch/wsBatch", ResponseNamespace:="http://tempuri.org/wsBatch/wsBatch", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub ResumeJob(ByVal jobExecutionCode As Long)
            Me.Invoke("ResumeJob", New Object() {jobExecutionCode})
        End Sub
        
        '''<remarks/>
        Public Function BeginResumeJob(ByVal jobExecutionCode As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ResumeJob", New Object() {jobExecutionCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndResumeJob(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ResumeJobAsync(ByVal jobExecutionCode As Long)
            Me.ResumeJobAsync(jobExecutionCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ResumeJobAsync(ByVal jobExecutionCode As Long, ByVal userState As Object)
            If (Me.ResumeJobOperationCompleted Is Nothing) Then
                Me.ResumeJobOperationCompleted = AddressOf Me.OnResumeJobOperationCompleted
            End If
            Me.InvokeAsync("ResumeJob", New Object() {jobExecutionCode}, Me.ResumeJobOperationCompleted, userState)
        End Sub
        
        Private Sub OnResumeJobOperationCompleted(ByVal arg As Object)
            If (Not (Me.ResumeJobCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ResumeJobCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsBatch/wsBatch/ResumeJobUpdateTotalItems", RequestNamespace:="http://tempuri.org/wsBatch/wsBatch", ResponseNamespace:="http://tempuri.org/wsBatch/wsBatch", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub ResumeJobUpdateTotalItems(ByVal jobExecutionCode As Long, ByVal totalItems As Long)
            Me.Invoke("ResumeJobUpdateTotalItems", New Object() {jobExecutionCode, totalItems})
        End Sub
        
        '''<remarks/>
        Public Function BeginResumeJobUpdateTotalItems(ByVal jobExecutionCode As Long, ByVal totalItems As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ResumeJobUpdateTotalItems", New Object() {jobExecutionCode, totalItems}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndResumeJobUpdateTotalItems(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ResumeJobUpdateTotalItemsAsync(ByVal jobExecutionCode As Long, ByVal totalItems As Long)
            Me.ResumeJobUpdateTotalItemsAsync(jobExecutionCode, totalItems, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ResumeJobUpdateTotalItemsAsync(ByVal jobExecutionCode As Long, ByVal totalItems As Long, ByVal userState As Object)
            If (Me.ResumeJobUpdateTotalItemsOperationCompleted Is Nothing) Then
                Me.ResumeJobUpdateTotalItemsOperationCompleted = AddressOf Me.OnResumeJobUpdateTotalItemsOperationCompleted
            End If
            Me.InvokeAsync("ResumeJobUpdateTotalItems", New Object() {jobExecutionCode, totalItems}, Me.ResumeJobUpdateTotalItemsOperationCompleted, userState)
        End Sub
        
        Private Sub OnResumeJobUpdateTotalItemsOperationCompleted(ByVal arg As Object)
            If (Not (Me.ResumeJobUpdateTotalItemsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ResumeJobUpdateTotalItemsCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsBatch/wsBatch/GetJobInfo", RequestNamespace:="http://tempuri.org/wsBatch/wsBatch", ResponseNamespace:="http://tempuri.org/wsBatch/wsBatch", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetJobInfo(ByVal jobExecutionCode As Long) As JobInfo
            Dim results() As Object = Me.Invoke("GetJobInfo", New Object() {jobExecutionCode})
            Return CType(results(0),JobInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetJobInfo(ByVal jobExecutionCode As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetJobInfo", New Object() {jobExecutionCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetJobInfo(ByVal asyncResult As System.IAsyncResult) As JobInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),JobInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetJobInfoAsync(ByVal jobExecutionCode As Long)
            Me.GetJobInfoAsync(jobExecutionCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetJobInfoAsync(ByVal jobExecutionCode As Long, ByVal userState As Object)
            If (Me.GetJobInfoOperationCompleted Is Nothing) Then
                Me.GetJobInfoOperationCompleted = AddressOf Me.OnGetJobInfoOperationCompleted
            End If
            Me.InvokeAsync("GetJobInfo", New Object() {jobExecutionCode}, Me.GetJobInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetJobInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetJobInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetJobInfoCompleted(Me, New GetJobInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsBatch/wsBatch/GetJobsId", RequestNamespace:="http://tempuri.org/wsBatch/wsBatch", ResponseNamespace:="http://tempuri.org/wsBatch/wsBatch", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetJobsId(ByVal jobSearchFilters As JobSearchFilters) As Long()
            Dim results() As Object = Me.Invoke("GetJobsId", New Object() {jobSearchFilters})
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Function BeginGetJobsId(ByVal jobSearchFilters As JobSearchFilters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetJobsId", New Object() {jobSearchFilters}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetJobsId(ByVal asyncResult As System.IAsyncResult) As Long()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetJobsIdAsync(ByVal jobSearchFilters As JobSearchFilters)
            Me.GetJobsIdAsync(jobSearchFilters, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetJobsIdAsync(ByVal jobSearchFilters As JobSearchFilters, ByVal userState As Object)
            If (Me.GetJobsIdOperationCompleted Is Nothing) Then
                Me.GetJobsIdOperationCompleted = AddressOf Me.OnGetJobsIdOperationCompleted
            End If
            Me.InvokeAsync("GetJobsId", New Object() {jobSearchFilters}, Me.GetJobsIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetJobsIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetJobsIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetJobsIdCompleted(Me, New GetJobsIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class JobInputData
        
        Private inputField As InputPort
        
        Private totalItemsField As Integer
        
        Private procedureIdField As Integer
        
        Private pausedField As Boolean
        
        '''<remarks/>
        Public Property Input() As InputPort
            Get
                Return Me.inputField
            End Get
            Set
                Me.inputField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalItems() As Integer
            Get
                Return Me.totalItemsField
            End Get
            Set
                Me.totalItemsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProcedureId() As Integer
            Get
                Return Me.procedureIdField
            End Get
            Set
                Me.procedureIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Paused() As Boolean
            Get
                Return Me.pausedField
            End Get
            Set
                Me.pausedField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class InputPort
        Inherits BasePort
        
        Private portConnectionsField() As PortConnection
        
        Private applicationIdField As String
        
        Private userIdField As Integer
        
        Private aziendaCodiceField As String
        
        Private dataRichiestaField As Date
        
        '''<remarks/>
        Public Property PortConnections() As PortConnection()
            Get
                Return Me.portConnectionsField
            End Get
            Set
                Me.portConnectionsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplicationId() As String
            Get
                Return Me.applicationIdField
            End Get
            Set
                Me.applicationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserId() As Integer
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AziendaCodice() As String
            Get
                Return Me.aziendaCodiceField
            End Get
            Set
                Me.aziendaCodiceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataRichiesta() As Date
            Get
                Return Me.dataRichiestaField
            End Get
            Set
                Me.dataRichiestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class PortConnection
        
        Private nameField As String
        
        Private connectionStringField As String
        
        Private providerField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConnectionString() As String
            Get
                Return Me.connectionStringField
            End Get
            Set
                Me.connectionStringField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Provider() As String
            Get
                Return Me.providerField
            End Get
            Set
                Me.providerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class JobSearchFilters
        
        Private idProceduraField As Integer
        
        Private idApplicativoField As String
        
        Private idUtenteField As Integer
        
        Private dataInizioRichiestaField As Date
        
        Private dataFineRichiestaField As Date
        
        '''<remarks/>
        Public Property IdProcedura() As Integer
            Get
                Return Me.idProceduraField
            End Get
            Set
                Me.idProceduraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdApplicativo() As String
            Get
                Return Me.idApplicativoField
            End Get
            Set
                Me.idApplicativoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdUtente() As Integer
            Get
                Return Me.idUtenteField
            End Get
            Set
                Me.idUtenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataInizioRichiesta() As Date
            Get
                Return Me.dataInizioRichiestaField
            End Get
            Set
                Me.dataInizioRichiestaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataFineRichiesta() As Date
            Get
                Return Me.dataFineRichiestaField
            End Get
            Set
                Me.dataFineRichiestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class TimeSpan
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class StatusInfo
        
        Private processedItemsField As Integer
        
        Private totalItemsField As Integer
        
        Private numberOfErrorsField As Integer
        
        Private startingTimeField As Date
        
        Private elapsedTimeField As TimeSpan
        
        Private statusField As StatusMode
        
        Private finishingTimeField As Date
        
        '''<remarks/>
        Public Property ProcessedItems() As Integer
            Get
                Return Me.processedItemsField
            End Get
            Set
                Me.processedItemsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalItems() As Integer
            Get
                Return Me.totalItemsField
            End Get
            Set
                Me.totalItemsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumberOfErrors() As Integer
            Get
                Return Me.numberOfErrorsField
            End Get
            Set
                Me.numberOfErrorsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartingTime() As Date
            Get
                Return Me.startingTimeField
            End Get
            Set
                Me.startingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ElapsedTime() As TimeSpan
            Get
                Return Me.elapsedTimeField
            End Get
            Set
                Me.elapsedTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As StatusMode
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FinishingTime() As Date
            Get
                Return Me.finishingTimeField
            End Get
            Set
                Me.finishingTimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Public Enum StatusMode
        
        '''<remarks/>
        PAUSED
        
        '''<remarks/>
        QUEUED
        
        '''<remarks/>
        RUNNING
        
        '''<remarks/>
        CANCELLED
        
        '''<remarks/>
        COMPLETED
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class JobInfo
        
        Private statusField As StatusInfo
        
        Private outputField As OutputPort
        
        Private idProcessoField As Long
        
        Private idUtenteField As Integer
        
        Private idProceduraField As Integer
        
        Private idApplicativoField As String
        
        Private dataRichiestaField As Date
        
        '''<remarks/>
        Public Property Status() As StatusInfo
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Output() As OutputPort
            Get
                Return Me.outputField
            End Get
            Set
                Me.outputField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdProcesso() As Long
            Get
                Return Me.idProcessoField
            End Get
            Set
                Me.idProcessoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdUtente() As Integer
            Get
                Return Me.idUtenteField
            End Get
            Set
                Me.idUtenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdProcedura() As Integer
            Get
                Return Me.idProceduraField
            End Get
            Set
                Me.idProceduraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdApplicativo() As String
            Get
                Return Me.idApplicativoField
            End Get
            Set
                Me.idApplicativoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DataRichiesta() As Date
            Get
                Return Me.dataRichiestaField
            End Get
            Set
                Me.dataRichiestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class OutputPort
        Inherits BasePort
        
        Private hasErrorsField As Boolean
        
        Private exceptionDetailField As String
        
        '''<remarks/>
        Public Property HasErrors() As Boolean
            Get
                Return Me.hasErrorsField
            End Get
            Set
                Me.hasErrorsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExceptionDetail() As String
            Get
                Return Me.exceptionDetailField
            End Get
            Set
                Me.exceptionDetailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(InputPort)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(OutputPort)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class BasePort
        
        Private portFilesField() As PortFileInfo
        
        Private portParametersField() As PortParameter
        
        '''<remarks/>
        Public Property PortFiles() As PortFileInfo()
            Get
                Return Me.portFilesField
            End Get
            Set
                Me.portFilesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PortParameters() As PortParameter()
            Get
                Return Me.portParametersField
            End Get
            Set
                Me.portParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class PortFileInfo
        
        Private nameField As String
        
        Private pathField As String
        
        Private parsingAlgorithmField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Path() As String
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParsingAlgorithm() As String
            Get
                Return Me.parsingAlgorithmField
            End Get
            Set
                Me.parsingAlgorithmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/wsBatch/wsBatch")>  _
    Partial Public Class PortParameter
        
        Private nameField As String
        
        Private valueField As Object
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub CreateJobCompletedEventHandler(ByVal sender As Object, ByVal e As CreateJobCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateJobCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ResumeJobCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ResumeJobUpdateTotalItemsCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetJobInfoCompletedEventHandler(ByVal sender As Object, ByVal e As GetJobInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetJobInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As JobInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),JobInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetJobsIdCompletedEventHandler(ByVal sender As Object, ByVal e As GetJobsIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetJobsIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
    End Class
End Namespace
