//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18444
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 

namespace Onit.OnAssistnet.OnVac.DIRV.ArchiviazioneSostitutiva
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class archiviazione_conservazione
    {
        private string enteField;

        private string areaOrgField;

        private string ufficioField;

        private string endUserIdField;

        private document[] documentsField;

        /// <remarks/>
        public string ente
        {
            get
            {
                return this.enteField;
            }
            set
            {
                this.enteField = value;
            }
        }

        /// <remarks/>
        public string areaOrg
        {
            get
            {
                return this.areaOrgField;
            }
            set
            {
                this.areaOrgField = value;
            }
        }

        /// <remarks/>
        public string ufficio
        {
            get
            {
                return this.ufficioField;
            }
            set
            {
                this.ufficioField = value;
            }
        }

        /// <remarks/>
        public string endUserId
        {
            get
            {
                return this.endUserIdField;
            }
            set
            {
                this.endUserIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("document", IsNullable = false)]
        public document[] documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class document
    {

        private string idClassificazioneField;

        private fileItem[] fileVectorField;

        /// <remarks/>
        public string idClassificazione
        {
            get
            {
                return this.idClassificazioneField;
            }
            set
            {
                this.idClassificazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("fileItem", IsNullable = false)]
        public fileItem[] fileVector
        {
            get
            {
                return this.fileVectorField;
            }
            set
            {
                this.fileVectorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class fileItem
    {

        private string fileNameField;

        private long fileShowOrderField;

        private bool fileShowOrderFieldSpecified;

        private long filePagesField;

        private bool filePagesFieldSpecified;

        private string fileHashTypeField;

        private string fileHashField;

        private string fileMimeField;

        private string fileMimeVersionField;

        private fileType fileTypeField;

        /// <remarks/>
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        public long fileShowOrder
        {
            get
            {
                return this.fileShowOrderField;
            }
            set
            {
                this.fileShowOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileShowOrderSpecified
        {
            get
            {
                return this.fileShowOrderFieldSpecified;
            }
            set
            {
                this.fileShowOrderFieldSpecified = value;
            }
        }

        /// <remarks/>
        public long filePages
        {
            get
            {
                return this.filePagesField;
            }
            set
            {
                this.filePagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filePagesSpecified
        {
            get
            {
                return this.filePagesFieldSpecified;
            }
            set
            {
                this.filePagesFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string fileHashType
        {
            get
            {
                return this.fileHashTypeField;
            }
            set
            {
                this.fileHashTypeField = value;
            }
        }

        /// <remarks/>
        public string fileHash
        {
            get
            {
                return this.fileHashField;
            }
            set
            {
                this.fileHashField = value;
            }
        }

        /// <remarks/>
        public string fileMime
        {
            get
            {
                return this.fileMimeField;
            }
            set
            {
                this.fileMimeField = value;
            }
        }

        /// <remarks/>
        public string fileMimeVersion
        {
            get
            {
                return this.fileMimeVersionField;
            }
            set
            {
                this.fileMimeVersionField = value;
            }
        }

        /// <remarks/>
        public fileType fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum fileType
    {

        /// <remarks/>
        D,

        /// <remarks/>
        X,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class documents
    {

        private document[] documentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("document")]
        public document[] document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class fileVector
    {

        private fileItem[] fileItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileItem")]
        public fileItem[] fileItem
        {
            get
            {
                return this.fileItemField;
            }
            set
            {
                this.fileItemField = value;
            }
        }
    }

}
