'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DatiVaccinaliPaziente

    '''<summary>
    '''OnitTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitTable1 As Global.Onit.Controls.OnitTable

    '''<summary>
    '''OnitSectionDatiAnagrafici control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitSectionDatiAnagrafici As Global.Onit.Controls.OnitSection

    '''<summary>
    '''OnitCellDatiAnagrafici control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitCellDatiAnagrafici As Global.Onit.Controls.OnitCell

    '''<summary>
    '''lblCognome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCognome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataNascita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComuneNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComuneNascita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodiceFiscale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodiceFiscale As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCittadinanza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCittadinanza As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSesso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatoAnagrafico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatoAnagrafico As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComuneResidenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComuneResidenza As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComuneDomicilio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComuneDomicilio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConsultorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConsultorio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OnitSectionLegendaDatiVaccinali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitSectionLegendaDatiVaccinali As Global.Onit.Controls.OnitSection

    '''<summary>
    '''OnitCellLegendaDatiVaccinali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitCellLegendaDatiVaccinali As Global.Onit.Controls.OnitCell

    '''<summary>
    '''OnitSectionDatiVaccinali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitSectionDatiVaccinali As Global.Onit.Controls.OnitSection

    '''<summary>
    '''OnitCellDatiVaccinali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitCellDatiVaccinali As Global.Onit.Controls.OnitCell

    '''<summary>
    '''dgrVacEseguite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrVacEseguite As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''dgrVacEscluse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrVacEscluse As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''dgrVisite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrVisite As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''dgrConvocazioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrConvocazioni As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lblCicliPaziente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCicliPaziente As Global.System.Web.UI.WebControls.Label
End Class
