'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RischioCicli
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''OnitLayout31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitLayout31 As Global.Onit.Controls.PagesLayout.OnitLayout3
    
    '''<summary>
    '''LayoutTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutTitolo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ToolBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBar As Global.Infragistics.WebUI.UltraWebToolbar.UltraWebToolbar
    
    '''<summary>
    '''pan_Vac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pan_Vac As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dgrRischioCicli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrRischioCicli As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''fmCicliRischio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmCicliRischio As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''InsCicli1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InsCicli1 As Global.Onit.OnAssistnet.OnVac.InsCicli
End Class
