'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace FlussoACN
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RicezioneFlussoACNCommand", [Namespace]:="http://schemas.datacontract.org/2004/07/OnVac.IntegrazioneVaccinazioni"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RicezioneFlussoACNCommand
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private flussoACNField As Onit.OnAssistnet.OnVac.Entities.FlussoACN
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property flussoACN() As Onit.OnAssistnet.OnVac.Entities.FlussoACN
            Get
                Return Me.flussoACNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.flussoACNField, value) <> true) Then
                    Me.flussoACNField = value
                    Me.RaisePropertyChanged("flussoACN")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RicezioneFlussoACNResult", [Namespace]:="http://schemas.datacontract.org/2004/07/OnVac.IntegrazioneVaccinazioni"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RicezioneFlussoACNResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="FlussoACN.IRicezioneFlussoACN")>  _
    Public Interface IRicezioneFlussoACN
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRicezioneFlussoACN/InserimentoAssociazioni", ReplyAction:="http://tempuri.org/IRicezioneFlussoACN/InserimentoAssociazioniResponse")>  _
        Function InserimentoAssociazioni(ByVal command As FlussoACN.RicezioneFlussoACNCommand) As FlussoACN.RicezioneFlussoACNResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRicezioneFlussoACN/ReinviaAssociazione", ReplyAction:="http://tempuri.org/IRicezioneFlussoACN/ReinviaAssociazioneResponse")>  _
        Function ReinviaAssociazione(ByVal idMessaggioPadre As String) As FlussoACN.RicezioneFlussoACNResult
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IRicezioneFlussoACNChannel
        Inherits FlussoACN.IRicezioneFlussoACN, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RicezioneFlussoACNClient
        Inherits System.ServiceModel.ClientBase(Of FlussoACN.IRicezioneFlussoACN)
        Implements FlussoACN.IRicezioneFlussoACN
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function InserimentoAssociazioni(ByVal command As FlussoACN.RicezioneFlussoACNCommand) As FlussoACN.RicezioneFlussoACNResult Implements FlussoACN.IRicezioneFlussoACN.InserimentoAssociazioni
            Return MyBase.Channel.InserimentoAssociazioni(command)
        End Function
        
        Public Function ReinviaAssociazione(ByVal idMessaggioPadre As String) As FlussoACN.RicezioneFlussoACNResult Implements FlussoACN.IRicezioneFlussoACN.ReinviaAssociazione
            Return MyBase.Channel.ReinviaAssociazione(idMessaggioPadre)
        End Function
    End Class
End Namespace
