'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StatAvvisoMantoux
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''OnitLayout31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitLayout31 As Global.Onit.Controls.PagesLayout.OnitLayout3
    
    '''<summary>
    '''PanelTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTitolo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LayoutTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutTitolo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Toolbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Toolbar As Global.Infragistics.WebUI.UltraWebToolbar.UltraWebToolbar
    
    '''<summary>
    '''Panel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel23 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LayoutTitolo_sezioneRicerca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutTitolo_sezioneRicerca As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dypScroll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dypScroll As Global.Onit.Web.UI.WebControls.DynamicPanel.DynamicPanel
    
    '''<summary>
    '''ucSelezioneConsultori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucSelezioneConsultori As Global.Onit.OnAssistnet.OnVac.SelezioneConsultori
    
    '''<summary>
    '''rblEseguita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEseguita As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lblDataEffettuazioneDa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataEffettuazioneDa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''odpDataMantouxDa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpDataMantouxDa As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''lblDataEffettuazioneA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataEffettuazioneA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''odpDataMantouxA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpDataMantouxA As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''fldDataInvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldDataInvio As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblDataInvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataInvio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDataInvioDa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataInvioDa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''odpDataInvioDa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpDataInvioDa As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''lblDataInvioA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataInvioA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''odpDataInvioA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpDataInvioA As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''lblDataNascitaDa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataNascitaDa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''odpDataNascitaDa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpDataNascitaDa As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''lblDataNascitaA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataNascitaA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''odpDataNascitaA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpDataNascitaA As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''rblPositiva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblPositiva As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''chklStatoAnagrafico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chklStatoAnagrafico As Global.Onit.OnAssistnet.Web.UI.WebControls.CheckBoxList.CheckBoxList
End Class
