'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace SistemaTsImmuni
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://sistematsimmuni.wsdl.sanita.finanze.it", ConfigurationName:="SistemaTsImmuni.sistemaTsImmuniPT")>  _
    Public Interface sistemaTsImmuniPT
        
        'CODEGEN: Generazione di un contratto di messaggio perché l'operazione sistemaTsImmuni non è RPC né incapsulata da documenti.
        <System.ServiceModel.OperationContractAttribute(Action:="http://sistematsimmuni.wsdl.sanita.finanze.it/SistemaTsImmuni", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function sistemaTsImmuni(ByVal request As SistemaTsImmuni.sistemaTsImmuniRequest) As SistemaTsImmuni.sistemaTsImmuniResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://sistematsimmunirichiesta.xsd.sanita.finanze.it")>  _
    Partial Public Class SistemaTsImmuniRichiesta
        
        Private idUtenteRichiedenteField As String
        
        Private pinCodeUtenteField As String
        
        Private codiceAnonimoTemporaneoField As String
        
        Private dataInizioSintomiField As String
        
        Private opzioniRequestField() As opzioniType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idUtenteRichiedente() As String
            Get
                Return Me.idUtenteRichiedenteField
            End Get
            Set
                Me.idUtenteRichiedenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property pinCodeUtente() As String
            Get
                Return Me.pinCodeUtenteField
            End Get
            Set
                Me.pinCodeUtenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property codiceAnonimoTemporaneo() As String
            Get
                Return Me.codiceAnonimoTemporaneoField
            End Get
            Set
                Me.codiceAnonimoTemporaneoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property dataInizioSintomi() As String
            Get
                Return Me.dataInizioSintomiField
            End Get
            Set
                Me.dataInizioSintomiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OpzioniRequest", Order:=4)>  _
        Public Property OpzioniRequest() As opzioniType()
            Get
                Return Me.opzioniRequestField
            End Get
            Set
                Me.opzioniRequestField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tipodatisistematsimmuni.xsd.sanita.finanze.it")>  _
    Partial Public Class opzioniType
        
        Private chiaveField As String
        
        Private valoreField As String
        
        Private tipoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property chiave() As String
            Get
                Return Me.chiaveField
            End Get
            Set
                Me.chiaveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property valore() As String
            Get
                Return Me.valoreField
            End Get
            Set
                Me.valoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://sistematsimmuniricevuta.xsd.sanita.finanze.it")>  _
    Partial Public Class SistemaTsImmuniRicevuta
        
        Private idTransazioneField As String
        
        Private timestampField As String
        
        Private esitoField As String
        
        Private descrizioneEsitoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property idTransazione() As String
            Get
                Return Me.idTransazioneField
            End Get
            Set
                Me.idTransazioneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property timestamp() As String
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property esito() As String
            Get
                Return Me.esitoField
            End Get
            Set
                Me.esitoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property descrizioneEsito() As String
            Get
                Return Me.descrizioneEsitoField
            End Get
            Set
                Me.descrizioneEsitoField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class sistemaTsImmuniRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sistematsimmunirichiesta.xsd.sanita.finanze.it", Order:=0)>  _
        Public SistemaTsImmuniRichiesta As SistemaTsImmuni.SistemaTsImmuniRichiesta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SistemaTsImmuniRichiesta As SistemaTsImmuni.SistemaTsImmuniRichiesta)
            MyBase.New
            Me.SistemaTsImmuniRichiesta = SistemaTsImmuniRichiesta
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class sistemaTsImmuniResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://sistematsimmuniricevuta.xsd.sanita.finanze.it", Order:=0)>  _
        Public SistemaTsImmuniRicevuta As SistemaTsImmuni.SistemaTsImmuniRicevuta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SistemaTsImmuniRicevuta As SistemaTsImmuni.SistemaTsImmuniRicevuta)
            MyBase.New
            Me.SistemaTsImmuniRicevuta = SistemaTsImmuniRicevuta
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface sistemaTsImmuniPTChannel
        Inherits SistemaTsImmuni.sistemaTsImmuniPT, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class sistemaTsImmuniPTClient
        Inherits System.ServiceModel.ClientBase(Of SistemaTsImmuni.sistemaTsImmuniPT)
        Implements SistemaTsImmuni.sistemaTsImmuniPT
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SistemaTsImmuni_sistemaTsImmuniPT_sistemaTsImmuni(ByVal request As SistemaTsImmuni.sistemaTsImmuniRequest) As SistemaTsImmuni.sistemaTsImmuniResponse Implements SistemaTsImmuni.sistemaTsImmuniPT.sistemaTsImmuni
            Return MyBase.Channel.sistemaTsImmuni(request)
        End Function

        Public Function sistemaTsImmuni(ByVal SistemaTsImmuniRichiesta As SistemaTsImmuni.SistemaTsImmuniRichiesta) As SistemaTsImmuni.SistemaTsImmuniRicevuta
            Dim inValue As SistemaTsImmuni.sistemaTsImmuniRequest = New SistemaTsImmuni.sistemaTsImmuniRequest()
            inValue.SistemaTsImmuniRichiesta = SistemaTsImmuniRichiesta
            Dim retVal As SistemaTsImmuni.sistemaTsImmuniResponse = CType(Me, SistemaTsImmuni.sistemaTsImmuniPT).sistemaTsImmuni(inValue)
            Return retVal.SistemaTsImmuniRicevuta
        End Function

    End Class
End Namespace
