'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GestioneAppuntamenti
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''mltView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mltView As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''viewGestioneAppuntamenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewGestioneAppuntamenti As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''OnitLayout31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OnitLayout31 As Global.Onit.Controls.PagesLayout.OnitLayout3
    
    '''<summary>
    '''LayoutTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutTitolo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ToolBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBar As Global.Infragistics.WebUI.UltraWebToolbar.UltraWebToolbar
    
    '''<summary>
    '''PanelRicerca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelRicerca As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblTitoloRicerca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitoloRicerca As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dypFiltri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dypFiltri As Global.Onit.Web.UI.WebControls.DynamicPanel.DynamicPanel
    
    '''<summary>
    '''table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents table1 As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''btnPulisciFiltri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPulisciFiltri As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab1 As Global.Infragistics.WebUI.UltraWebTab.UltraWebTab
    
    '''<summary>
    '''lblFiltroCicSed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFiltroCicSed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnImgCicliSedute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImgCicliSedute As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblCicliSedute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCicliSedute As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnImgAssociazioniDosi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImgAssociazioniDosi As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblAssociazioniDosi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssociazioniDosi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fmComune control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmComune As Global.Onit.Controls.OnitModalList
    
    '''<summary>
    '''ucSelezioneConsultori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucSelezioneConsultori As Global.Onit.OnAssistnet.OnVac.SelezioneConsultori
    
    '''<summary>
    '''txtMedico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMedico As Global.Onit.Controls.OnitModalList
    
    '''<summary>
    '''ddlSesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSesso As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkCronici control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCronici As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''omlCategorieRischio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents omlCategorieRischio As Global.Onit.Controls.OnitModalList
    
    '''<summary>
    '''omlMalattia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents omlMalattia As Global.Onit.Controls.OnitModalList
    
    '''<summary>
    '''chkImmigratiNonExtracomPrimaVolta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImmigratiNonExtracomPrimaVolta As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkImmigratiExtracom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImmigratiExtracom As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtDaDataNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDaDataNascita As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''txtADataNascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtADataNascita As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''chkSoloRitardatari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSoloRitardatari As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDataSingola control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDataSingola As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkEscluse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEscluse As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblUltimaData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUltimaData As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFinoAData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFinoAData As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''lblDataIniz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataIniz As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''odpDataInizPrenotazioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpDataInizPrenotazioni As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''lblDataFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataFin As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''odpDataFinePrenotazioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odpDataFinePrenotazioni As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''btnOrariPers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrariPers As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkOrariPers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOrariPers As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hid_txt_num_orari_pers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hid_txt_num_orari_pers As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkSovrapponiRit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSovrapponiRit As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkFiltroPomeriggioObbligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFiltroPomeriggioObbligatorio As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ucStatiAnagrafici control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucStatiAnagrafici As Global.Onit.OnAssistnet.OnVac.Common.Controls.StatiAnagrafici
    
    '''<summary>
    '''chkTipoVaccObbligatoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTipoVaccObbligatoria As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkTipoVaccFacoltativa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTipoVaccFacoltativa As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkTipoVaccRaccomandata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTipoVaccRaccomandata As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkRicConvocazioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRicConvocazioni As Global.Onit.OnAssistnet.Web.UI.WebControls.CheckBox.CheckBox
    
    '''<summary>
    '''chkRicCiclo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRicCiclo As Global.Onit.OnAssistnet.Web.UI.WebControls.CheckBox.CheckBox
    
    '''<summary>
    '''chkRicMedico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRicMedico As Global.Onit.OnAssistnet.Web.UI.WebControls.CheckBox.CheckBox
    
    '''<summary>
    '''chkRicBilancio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRicBilancio As Global.Onit.OnAssistnet.Web.UI.WebControls.CheckBox.CheckBox
    
    '''<summary>
    '''btnRicApplica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRicApplica As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkOrdineAlfabeticoRicerca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOrdineAlfabeticoRicerca As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtNumPazientiAlGiorno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPazientiAlGiorno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDurata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDurata As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumNuoviPazientiAlGiorno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumNuoviPazientiAlGiorno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkOrdineAlfabeticoPrenotazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOrdineAlfabeticoPrenotazione As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblRis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRis As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dypScroll1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dypScroll1 As Global.Onit.Web.UI.WebControls.DynamicPanel.DynamicPanel
    
    '''<summary>
    '''panelOrdinamenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelOrdinamenti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tableStampaConvocati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableStampaConvocati As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''btnStampaSelezionati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStampaSelezionati As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkSelDeselDtaRicercaConvocati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSelDeselDtaRicercaConvocati As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblNumeroPagine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroPagine As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dlsRicercaConvocati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlsRicercaConvocati As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''DivCal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivCal As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LabelCal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dypCalendario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dypCalendario As Global.Onit.Web.UI.WebControls.DynamicPanel.DynamicPanel
    
    '''<summary>
    '''txtVaiAData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVaiAData As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''btnAssegna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAssegna As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Calendario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calendario As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''Tab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab2 As Global.Infragistics.WebUI.UltraWebTab.UltraWebTab
    
    '''<summary>
    '''imgls_Mattino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgls_Mattino As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''lsMattino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsMattino As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''imgls_Pomeriggio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgls_Pomeriggio As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''lsPomeriggio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsPomeriggio As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''pnlOpzioniAppuntamenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOpzioniAppuntamenti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkAppConvocazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAppConvocazione As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkAppDurata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAppDurata As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnAppApplica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAppApplica As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkAppMedico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAppMedico As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkAppVaccinazioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAppVaccinazioni As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkAppInBilancio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAppInBilancio As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtEspanso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEspanso As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFiltri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFiltri As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dypMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dypMsg As Global.Onit.Web.UI.WebControls.DynamicPanel.DynamicPanel
    
    '''<summary>
    '''lblMessaggi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessaggi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fmPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmPopUp As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''lblMessaggio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessaggio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnOrariApertura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrariApertura As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fmLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmLog As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''lblLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLog As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnChiudiLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChiudiLog As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnStampaLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStampaLog As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fmFiltroAssociazioniDosi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmFiltroAssociazioniDosi As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''UscFiltroAssociazioniDosi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UscFiltroAssociazioniDosi As Global.Onit.OnAssistnet.OnVac.UscFiltroPrenotazioneSelezioneMultipla
    
    '''<summary>
    '''btnOk_FiltroAssociazioniDosi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk_FiltroAssociazioniDosi As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAnnulla_FiltroAssociazioniDosi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnulla_FiltroAssociazioniDosi As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fmFiltroCicliSedute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmFiltroCicliSedute As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''UscFiltroCicliSedute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UscFiltroCicliSedute As Global.Onit.OnAssistnet.OnVac.UscFiltroPrenotazioneSelezioneMultipla
    
    '''<summary>
    '''btnOk_FiltroCicliSedute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk_FiltroCicliSedute As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAnnulla_FiltroCicliSedute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnulla_FiltroCicliSedute As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fmOrariPersonalizzati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmOrariPersonalizzati As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''tlbOrariPersonalizzati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tlbOrariPersonalizzati As Global.Infragistics.WebUI.UltraWebToolbar.UltraWebToolbar
    
    '''<summary>
    '''dgrOrariPersonalizzati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrOrariPersonalizzati As Global.Onit.Controls.OnitGrid.OnitGrid
    
    '''<summary>
    '''fmSpostaPrenotazioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmSpostaPrenotazioni As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''fldSpostaPrenotazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldSpostaPrenotazione As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Legend1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Legend1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dpkDataSpostamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpkDataSpostamento As Global.Onit.Web.UI.WebControls.Validators.OnitDatePick
    
    '''<summary>
    '''SpostaSceltaAmb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpostaSceltaAmb As Global.Onit.OnAssistnet.OnVac.Common.Controls.AjaxList
    
    '''<summary>
    '''btnOkSposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOkSposta As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAnnullaSposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnullaSposta As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fmSceltaAmb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmSceltaAmb As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''ambAjaxlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ambAjaxlist As Global.Onit.OnAssistnet.OnVac.Common.Controls.AjaxList
    
    '''<summary>
    '''fmAvviaRicerca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmAvviaRicerca As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''lblAvviaRicerca_Solleciti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvviaRicerca_Solleciti As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnAvviaRicerca_OperazioniERicerca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAvviaRicerca_OperazioniERicerca As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnAvviaRicerca_SoloRicerca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAvviaRicerca_SoloRicerca As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''fmConsensoUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmConsensoUtente As Global.Onit.Controls.OnitFinestraModale
    
    '''<summary>
    '''ucConsensoUtente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucConsensoUtente As Global.Onit.OnAssistnet.OnVac.ConsensoTrattamentoDatiUtente
    
    '''<summary>
    '''viewGestioneSolleciti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewGestioneSolleciti As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ToolBarGestioneSolleciti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolBarGestioneSolleciti As Global.Infragistics.WebUI.UltraWebToolbar.UltraWebToolbar
    
    '''<summary>
    '''dypTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dypTab As Global.Onit.Web.UI.WebControls.DynamicPanel.DynamicPanel
    
    '''<summary>
    '''ultraTabRiepilogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ultraTabRiepilogo As Global.Infragistics.WebUI.UltraWebTab.UltraWebTab
    
    '''<summary>
    '''imgPazientiDaSollecitare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPazientiDaSollecitare As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPazientiDaSollecitare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazientiDaSollecitare As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNessunPazienteDaSollecitare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNessunPazienteDaSollecitare As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPazSollLimitato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazSollLimitato As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divPazientiDaSollecitare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPazientiDaSollecitare As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgrPazientiDaSollecitare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrPazientiDaSollecitare As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''imgPazientiInTerminePerentorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPazientiInTerminePerentorio As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPazientiInTerminePerentorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazientiInTerminePerentorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNessunPazienteTerminePerentorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNessunPazienteTerminePerentorio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPazTPLimitato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazTPLimitato As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divPazientiInTerminePerentorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPazientiInTerminePerentorio As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgrPazientiInTerminePerentorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrPazientiInTerminePerentorio As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''imgPazientiElimProgRicalcolaConv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPazientiElimProgRicalcolaConv As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPazientiElimProgRicalcolaConv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazientiElimProgRicalcolaConv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNessunPazienteElimProgRicalcolaConv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNessunPazienteElimProgRicalcolaConv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPazElimProgLimitato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazElimProgLimitato As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DivPazientiElimProgRicalcolaConv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivPazientiElimProgRicalcolaConv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgrPazientiVaccinazioniRaccomandate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrPazientiVaccinazioniRaccomandate As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''imgPazientiPosticipaVaccNonObbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPazientiPosticipaVaccNonObbl As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPazientiPosticipaVaccNonObbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazientiPosticipaVaccNonObbl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNessunPazientePosticipaVaccNonObbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNessunPazientePosticipaVaccNonObbl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPazPostLimitato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazPostLimitato As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divPazientiPosticipaVaccNonObbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPazientiPosticipaVaccNonObbl As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgrPazientiVaccinazioniNonObbligatorie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrPazientiVaccinazioniNonObbligatorie As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''imgPazientiNoCiclo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPazientiNoCiclo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPazientiNoCiclo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazientiNoCiclo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNessunPazienteNoCiclo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNessunPazienteNoCiclo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPazNoCicloLimitato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazNoCicloLimitato As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divPazientiNoCiclo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPazientiNoCiclo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgrPazientiNoCiclo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrPazientiNoCiclo As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''Image3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPazientiDisallineati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazientiDisallineati As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNessunPazienteDisallineati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNessunPazienteDisallineati As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPazientiLimitatiDisallineati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPazientiLimitatiDisallineati As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divPazientiDisallineati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPazientiDisallineati As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dgrDisallineati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgrDisallineati As Global.System.Web.UI.WebControls.DataGrid
End Class
